version: 2
updates:
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: weekly
    groups:
      ef-core:
        patterns:
          - "Microsoft.EntityFrameworkCore*"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
