using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations.Operations;

namespace EntityFrameworkCore.ExtensibleMigrations;

/// <summary>
/// Interface for handlers that contribute migration operations based on model differences.
/// </summary>
public interface IMigrationOperationHandler
{
    /// <summary>
    /// Gets additional migration operations based on model differences.
    /// </summary>
    /// <param name="source">The source relational model (previous state)</param>
    /// <param name="target">The target relational model (current state)</param>
    /// <param name="existingOperations">Operations already generated by the default differ and other handlers</param>
    /// <returns>Additional operations to add to the migration</returns>
    IReadOnlyList<MigrationOperation> GetOperations(
        IRelationalModel? source,
        IRelationalModel? target,
        IReadOnlyList<MigrationOperation> existingOperations
    );

    /// <summary>
    /// Determines if there are differences that require a migration.
    /// </summary>
    /// <param name="source">The source relational model</param>
    /// <param name="target">The target relational model</param>
    /// <param name="defaultHasDifferences">Whether the default differ detected differences</param>
    /// <returns>True if there are differences requiring a migration</returns>
    bool HasDifferences(
        IRelationalModel? source,
        IRelationalModel? target,
        bool defaultHasDifferences
    );
}
