// <auto-generated>
// Injected into the consumer's compile by EntityFrameworkCore.ExtensibleMigrations
// via buildTransitive/EntityFrameworkCore.ExtensibleMigrations.targets.
//
// EF Core discovers IDesignTimeServices types directly implemented in the
// startup project assembly AFTER the database provider's design-time services
// run, so our wrappers correctly sit on top of provider-overridden services.
//
// [assembly: DesignTimeServicesReference] alone is insufficient because EF
// runs referenced design-time services BEFORE provider services, so a wrap
// registered there gets overwritten by the provider.
// </auto-generated>
namespace EntityFrameworkCore.ExtensibleMigrations.Generated
{
    internal sealed class _ExtensibleMigrationsAutoDesignTimeServices
        : Microsoft.EntityFrameworkCore.Design.IDesignTimeServices
    {
        public void ConfigureDesignTimeServices(
            Microsoft.Extensions.DependencyInjection.IServiceCollection services)
            => new EntityFrameworkCore.ExtensibleMigrations.ExtensibleMigrationsDesignTimeServices()
                .ConfigureDesignTimeServices(services);
    }
}
